### ISSUE TITLE
SRH_pitch.m has serious issues with long files

### ISSUE THREAD

**Issue by schererstefan** [covarep/covarep#49]
memory goes out of reasonable bounds. 
i will fix it with a temporary workaround:

specMat = zeros(fs, size(frameMatWinMean,2));
for i = 1:size(frameMatWinMean,2)
    specMat(:,i) = abs( fft(frameMatWinMean(:,i),fs) )';
end

in addition i will add clear commands to delete unnecessary matrices whenever possible.

**Comment by gillesdegottex** [comment]
Hey @schererstefan , did you commit something for this eventually ?
Can we close this issue ?

Or should we resurect the previous implementation and let the user chose between the two as @jckane suggested ?

Cheers

**Comment by gillesdegottex** [comment]
Should be checked again, regarding #61

**Comment by schererstefan** [comment]
Indeed my student twoertwein is taking a look at this right now. I think he might have found some solution.

**Comment by twoertwein** [comment]
The current version of pitch_srh does not use the vectorised approach. From my point of view that should not be an issue since Stefan's initial change to save memory was not the bottle neck in terms of CPU time. Of course, it would be nice to enable the vectorised approach for small files. However, I think that after the latest changes pitch_srh is fast enough, even without the vectorisation.

If you want to make COVAREP faster you should use MATLAB's 'Run and Time' feature to profile the feature extraction process. You will notice that 'hpfilter_fir' in 'iaif_gci.m' uses most of the time. You may also want to rewrite some parts of the creaky voice detection (i.e. get_creak_h2h1).

**Comment by gillesdegottex** [comment]
Closing this issue, regarding improvements brought in #62.

(Please re-open if I missed a point)
