### ISSUE TITLE
SRH_pitch.m breaks if audio has lower sample rate than 16kHz

### ISSUE THREAD

**Issue by schererstefan** [covarep/covarep#50]
Currently the frequency check only tests if sample rate is above 16kHz and then down-samples the audio to 16kHz. I suggest to change this to capture frequencies that are "not equal" to 16000 and change them.

Line 77: if fs~=16000

**Comment by gillesdegottex** [comment]
The sound sample above was not passing because its sampling rate is odd (11025).
Thus, it was not related to fs<16kHz.

I pushed a fix for this and I changed the condition of resample with fs>16000.
I don't see any problem why it shouln't work with any other fs<16kHz.
(and the sound sample above works now).

Thus, closing this issue.
