### ISSUE TITLE
Add Robust Voice Activity Detection (T. Drugman)

### ISSUE THREAD

**Issue by gillesdegottex** [covarep/covarep#52]

**Comment by gillesdegottex** [comment]
Demo HOWTO_VAD.m doesn't run on my machine because of my simuli toolbox version.
Need someone to run it !
(@jckane ?)

**Comment by gillesdegottex** [comment]
@ThomasDrugman , please run it too, to check it.

**Comment by jckane** [comment]
Hey Gilles

I'll try run it tomorrow. I only have Octave on my current machine though.

**Comment by gillesdegottex** [comment]
Ouch, I think there is currently no proper Octave toolbox to replace simulink (or at the neural net stuffs, remember the creaky detector).
Forget it, let's see first what Tom think about it.
Cheers

**Comment by jckane** [comment]
OK sorry about that.

I am actually going to be doing some collaborative work on GCIs soon. I'll
make sure the code is made available here. Though it is currently a C
implementation.

**Comment by gillesdegottex** [comment]
If the C code is pure std, you could make a mex interface. This would justify it as a Matlab-compatible code ... though not Octave-compatible surely (or there are also techniques similar to mex in Octave ?).

Otherwise, we should really start thinking about parallel repositories in C/C++ (and Python one day).

**Comment by nshmyrev** [comment]
C/Python part is definitely needed!

**Comment by jckane** [comment]
I believe that the code is indeed Standard Library (STL), so that should be
fine. I try a mex it one I get the work done on it.

We need to think about how we should incorporate different languages. Your
suggestion of parallel repositories seems like a good one. We may wish to
have one language (e.g., Matlab/Octave) always be the reference and that
other language algorithm implementations will need to regression test to
Matlab implementation.

On 16 March 2015 at 12:02, Gilles Degottex <notifications@github.com> wrote:

> If the C code is pure std, you could make a mex interface. This would
> justify it as a Matlab-compatible code ... though not Octave-compatible
> surely (or there are also techniques similar to mex in Octave ?).
>
> Otherwise, we should really start thinking about parallel repositories in
> C/C++ (and Python one day).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/covarep/covarep/issues/52#issuecomment-81607926>.
>



-- 
Post-doctoral researcher

Phonetics and Speech Laboratory (Room 4074)
Arts Block,
Centre for Language and Communication Studies,
School of Linguistics, Speech and Communication Sciences,
Trinity College Dublin,
College Green
Dublin 2

Phone:    (+353) 1 896 1348
Website:
http://www.tcd.ie/slscs/postgraduate/phd-masters-research/student-pages/johnkane.php

Check out COVAREP - A co-operative voice analysis repository for speech
technologies:
*Website:* http://covarep.github.io/covarep/
*GitHub: *https://github.com/covarep/covarep

**Comment by gillesdegottex** [comment]
@ThomasDrugman checked it. Working.
Ready for next release.
