### ISSUE TITLE
Support for other languages ? C/C++ ? Python ?

### ISSUE THREAD

**Issue by gillesdegottex** [covarep/covarep#56]
(Please see begining of the discussion in issue #52, copy/paste below)
(Please @jckane @nshmyrev, continue here)

gillesdegottex: Otherwise, we should really start thinking about parallel repositories in C/C++ (and Python one day).

nshmyrev: C/Python part is definitely needed!

jckane: We need to think about how we should incorporate different languages. Your
suggestion of parallel repositories seems like a good one. We may wish to
have one language (e.g., Matlab/Octave) always be the reference and that
other language algorithm implementations will need to regression test to
Matlab implementation.

**Comment by gillesdegottex** [comment]
I like the idea of having a reference language.
And I see there is clear request for Python :)

With parallel repos, we would have to ensure the symmetry between the folder's trees (proper expression John ?).
With a single tree and all implementations in the same directory (envelope/env_dap.m; envelope/env_dap.cpp; envelope/env_dap.py), would this be easier to manage and easier to know which implementation exists ? (looks a bit more messy though)

**Comment by gillesdegottex** [comment]
I remember the argument we had about C/C++ when creating COVAREP:
C/C++ implementations might be harder and more complex to build (harder to debug, need to link with external libraries (eg. for linear algebra)). Thus, we were expecting to have a bit of money (eg. from project) to start going into this direction.

However, if someone want to provide a C/C++ implementation, this would be a real pity to block it, for reason of principles.

**Comment by traitio** [comment]
Parallel repositories e.g. in C/C++ might be suitalbe for some (simple) algorithms, but some programs are just not good for Matlab. A solution might be that some algorithms are implemented using several or all languages, some just in one or two. For example GlottHMM is not practical in Matlab, but I can put it in the C repository. GlottHMM is coded in C but it requires some external libraries, so it works only as Matlab/MEX if the libraries are installed. Does that count for a Matlab repository?

**Comment by gillesdegottex** [comment]
Hi all,

I just started an MSCA Fellowship and I planned to release everything I'll do in Open-source using LGPL license. Because I'll prefer Python over Matlab, I would like to resurrect this thread for starting a "PYVAREP" repository (which would belong to the COVAREP organization).

For a starter, I would like to add Harmonic Models analysis/synthesis and some envelope estimation methods.

A few point to settle before starting:
* I think we should go for separate parallel repositories. Putting everything in the same repository (e.g. the current COVAREP) would end up to be too messy.
* Note that a repository can use some code of another one. Thus, the current Matlab repo could use the C repo for compiling mex files.
* To ensure minimum consistency between the repos, we might need a simple rule : If a function is added, its interface should follow that of its implementation in another language(s). If the function doesn't exist in another language, the developer/maintainer is free to implement it with the interface he/she wants.
* We can also create the "CCVAREP" repo for C/C++, if someone has something to add right away.

What do you think guys ?
See anything else to discuss ?

Cheers,
(cc: @traitio, @jckane, @schererstefan, @ThomasDrugman)

**Comment by ThomasDrugman** [comment]
Hi Gilles,

Thank you for the suggestion.
While I have a pretty good idea of the workload this represents, I can hardly quantify the possible outcome.

At the first glance, it looks like a lot of efforts, for possibly not much at the output.

What do you think?
Do you really believe there is a high demand to translate the code to Python (given that these methods are already publicly available in Matlab)?

Thomas


De : Gilles Degottex [mailto:notifications@github.com]
Envoyé : mardi 6 octobre 2015 12:45
À : covarep/covarep
Cc : Thomas DRUGMAN [530408]
Objet : Re: [covarep] Support for other languages ? C/C++ ? Python ? (#56)


Hi all,

I just started an MSCA Fellowship and I planned to release everything I'll do in Open-source using LGPL license. Because I'll prefer Python over Matlab, I would like to resurrect this thread for starting a "PYVAREP" repository (which would belong to the COVAREP organization).

For a starter, I would like to add Harmonic Models analysis/synthesis and some envelope estimation methods.

A few point to settle before starting:

  *   I think we should go for separate parallel repositories. Putting everything in the same repository (e.g. the current COVAREP) would end up to be too messy.
  *   Note that a repository can use some code of another one. Thus, the current Matlab repo could use the C repo for compiling mex files.
  *   To ensure minimum consistency between the repos, we might need a simple rule : If a function is added, its interface should follow that of its implementation in another language(s). If the function doesn't exist in another language, the developer/maintainer is free to implement it with the interface he/she wants.
  *   We can also create the "CCVAREP" repo for C/C++, if someone has something to add right away.

What do you think guys ?
See anything else to discuss ?

Cheers,
(cc: @traitio<https://github.com/traitio>, @jckane<https://github.com/jckane>, @schererstefan<https://github.com/schererstefan>, @ThomasDrugman<https://github.com/ThomasDrugman>)

**Comment by gillesdegottex** [comment]
I didn't mean to translate everything.
When I wrote "parallel" (and this is what I've understood from the previous discussion), the idea is only to ensure a minimum of consistency between the repositories of different languages (e.g. if two functions exist in two languages, they use the same arguments, return the same values, etc.).

Thus, at the beginning, at least for me, the workload would be to re-implement only the harmonic model and some envelope estimation methods.

**Comment by schererstefan** [comment]
Just wanted to let you guys know that matlab 2015b apparently now can also export python libraries. I'll compile the current project and you can try the python library if you want.

**Comment by gillesdegottex** [comment]
I don't see anybody to do nor maintain such a port of COVAREP in Python or any other language.
Closing.
