### ISSUE TITLE
How-tos Envelope and Sinusoidal (empty "frames" structure)

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#69]
Hej again.

Same file and system: (https://www.dropbox.com/s/00dqqrs56jkq2nr/sc1_1.wav?dl=0) on Matlab 2015b (OS X, Yosemite).

Trying to run either envelope or sinusoidal gives a crash due to "frames" not being properly generated:

> Some windows were outside of the signal. 1 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).

This generates the following errors

Sinusoidal

> Struct contents reference from a non-struct array object.
> Error in sin_analysis (line 407)
>        if opt.debug>0; disp(['Mean SNR=' num2str(mean([frames.SNR]))]); end
> Error in HOWTO_sinusoidal (line 43)
> [frames syn_sm] = sin_analysis(wav, fs, f0s, opt);

Envelope

> Struct contents reference from a non-struct array object.
> Error in HOWTO_envelope (line 50)
> srh_f0 = interp1(srh_time, srh_f0, [frames.t]);

**Comment by gillesdegottex** [comment]
I don't have an OSX myself so I cannot test everything.
However, using:

[srh_f0,srh_vuv,srh_vuvc,srh_time] = pitch_srh(wav,fs,70,500,10);
f0s = [srh_time(:), srh_f0(:)];

for computing the f0s (instead of the txt file), everything works fine.
Could you try these two lines on your side ?

(note that this sound file seems to be compressed (there is a lot of holes in the spectrum), that's surely not a good thing for most of the analysis methods in COVAREP).

**Comment by fusaroli** [comment]
This works! Thanks.
