### ISSUE TITLE
error: griddedinterpolant meets an error

### ISSUE THREAD

**Issue by leocnj** [covarep/covarep#76]
```
An error occurred while analysing 01_segment-01: Error using griddedInterpolant
Interpolation requires at least two sample points in each dimension.

Error in interp1 (line 161)
        F = griddedInterpolant(X,V,method);

Error in COVAREP_feature_extraction (line 123)
        VUV_int = interp1(round(srh_time*fs),srh_vuv,1:length(x));
```

**Comment by leocnj** [comment]
I am using Matlab R2015b on Win7 64 bit. Even trying the three audio files existing in covarep-master, I still met the same error message.

**Comment by gillesdegottex** [comment]
Sorry for the very late reply Lei.

Can you drop me the file you're using somewhere (e.g. dropbox link)?

@schererstefan do you have a few minutes to check that the features extraction work on the demo audio files?

**Comment by gillesdegottex** [comment]
I just checked the demonstration files:
COVAREP_feature_extraction works flawlessly on arctic_a0007.wav and 0011.arctic_bdl1.wav.

@leocnj, can you check if there is any differences between the matlab files you're using and those of the master ? (or any other COVAREP version)

glottalized-m1.wav doesn't work because it is too short (260ms duration) for HMPD analysis.
I don't plan to manage such short files.

**Comment by gillesdegottex** [comment]
Seems dead thread.
Will be re-opened if more news.
