### ISSUE TITLE
some questions about the Fan-Chirp transform

### ISSUE THREAD

**Issue by xjtusz** [covarep/covarep#92]
Hi,I download fcht.m and find it's very slow especially when the signal is long.I read the reference of your routine called "Adaptive Chirp-based time-frequency analysis of speech signals'' , and in this paper,the author said we use fft to compute fcht,but it seems you don't use fft in your routine. Is this the reason that your routine is slow?

**Comment by gillesdegottex** [comment]
Hi,

Only the raw implementation of FChT equations have been implemented in COVAREP.

I don't really know what means "we use FFT to compute FChT", since the FFT frequency basis is stationary harmonic and I really doubt the FFT algo optimisation is still valid with non-stationary basis. Does it mean frequency demodulation prior to FFT? but in this case it wouldn't be FChT anymore ...
